Event.UI/Controllers/RunnerController.cs
using CouponFactory.Core.Models;
using Event.Core.Models;
using Event.Services.Classes.Runner;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Event.UI.Controllers
{
    public class RunnerController : Controller
    {
        // GET: Runner
        public ActionResult Index()
        {
            RunnerModel runnerModel = new RunnerModel();

            //var citiesList = new SelectList(
            //    new List<SelectListItem>
            //    {
            //        new SelectListItem {Text = "Bath", Value = "Bath"},
            //        new SelectListItem {Text = "Birmingham ", Value = "Birmingham "},
            //         new SelectListItem {Text = "Bangor ", Value = "Bangor "},
            //          new SelectListItem {Text = "Newport ", Value = "Newport "},
            //          new SelectListItem {Text = "Aberdeen ", Value = "Aberdeen "},
            //          new SelectListItem {Text = "Lisburn  ", Value = "Lisburn  "},
            //    }, "Value", "Text");

            return View(runnerModel);
        }

        /// <summary>
        /// Register new Runner
        /// </summary>
        /// <param name="runnerModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Register(RunnerModel runnerModel)
        {

            ViewBag.Message = "Error occurred. Please try again after sometime.";
            try
            {
                if (ModelState.IsValid)
                {
                    bool result = RunnerManager.UpdateRunner(runnerModel);
                    ViewBag.Message = (result) ? "Thanks for registration" : "Error occurred. Please try again after sometime.";
                    return View("~/Views/Runner/AfterRegistartion.cshtml");
                }
                return View("~/Views/Runner/AfterRegistartion.cshtml");
            }
            catch (Exception ex)
            {

            }
            return View("~/Views/Runner/AfterRegistartion.cshtml");
        }


        /// <summary>
        /// Get Brands List
        /// </summary>
        /// <param name="parms"></param>
        /// <returns></returns>
        public async Task<ActionResult> List(jQueryDataTableParamModel parms)
        {
            var programs = await RunnerManager.GetRunnersDataTable(parms);
            return Json(new
            {
                aaData = programs.Item1,
                iTotalRecords = programs.Item3,
                iTotalDisplayRecords = programs.Item3
            }, JsonRequestBehavior.AllowGet);

        }

    }
}

Event.UI/Views/Runner/AfterRegistartion.cshtml
@{
    ViewBag.Title = ViewBag.Message;
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

   

Event.UI/Views/Runner/Index.cshtml
@model Event.Core.Models.RunnerModel
@{
    ViewBag.Title = "Runner Registration ";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

@using (Html.BeginForm("Register", "Runner", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{

    @Html.HiddenFor(x => x.IsAddedByAdmin, new { Value = 0 })
    <div class="card-body">
        <div class="form-group">
            <label for="Name">Name</label>
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label for="Address">Address</label>
            @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="HostingCity">Hosting City</label>
            @Html.TextBoxFor(x => x.HostingCity, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.HostingCity, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label for="Route">Route</label>
            @*@Html.DropDownListFor(x => x.Route, new SelectList(Model.LstRoutes, "Value", "Text", Model.Route), "Select Route", new
                {
                    @class = "form-control",
                    //data_select_parent = "true",
                    //data_child_data_url = "regionmaster/getregionstatesbycountryid?countryId=",
                    //data_select_parent_id = "CountryId",
                    //data_child_selector = "StateId"
                })*@
            @Html.EnumDropDownListFor(x => x.Route, "Select Route", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Route, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label for="Charity">Charity</label>
            @Html.TextBoxFor(x => x.Charity, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Charity, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label for="CharityFund">Charity Fund</label>
            @Html.TextBoxFor(x => x.CharityFund, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CharityFund, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label for="Category">Category</label>
            @Html.EnumDropDownListFor(x => x.Category, "Select Category", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Category, "", new { @class = "text-danger" })
        </div>
    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <button type="submit" class="btn btn-primary btn-block">Register</button>

        <p class="my-2">
            <a href="@Url.Action("Login", "Account")">Login if you have access</a>
        </p>
    </div>
}